### ISSUE TITLE
Avoid warning for inter-relative extra dependencies

### ISSUE THREAD

**Issue by CasperWA** [SINTEF/ci-cd#198]
In the `update-deps` task, there is no need to warn if an inter-relative extra dependency is found, e.g.:

```toml
[project]
name = "ci-cd"

[project.optional-dependencies]
testing = ["pytest", "pytest-cov"]
dev = ["pre-commit", "ci-cd[testing]"]
```

Here, the `ci-cd[testing]` dependency should be ignored.
